name: training_and_testing
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  dio: ^5.1.1
  easy_localization: ^3.0.1
  flutter:
    sdk: flutter
  flutter_form_builder: ^8.0.0
  flutter_svg: ^2.0.4
  font_awesome_flutter: ^10.4.0
  form_builder_validators: ^8.5.0
  get: ^4.6.5
  go_router: ^6.5.5
  google_sign_in: ^6.0.2
  intl: 0.17.0
  reactive_forms: ^14.1.0
  shared_preferences: ^2.0.20

  catalog_api:
    path: packages/catalog_api
  flutter_animate: ^4.1.1+1
  grouped_list: ^5.1.2
  flutter_sticky_header: ^0.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
